version: '3.9'
services:
  webserver:
    build:
      context: ./.docker/server_http
      args:
        TIMEZONE: ${TIMEZONE}
    labels:
      ho.ctf.cyrhades: "1"
    ports:
      - ${PORT}:80
    restart: always
    volumes:
      - web:/var/www/html
  ftp.hotelgrosdodo.fr:
    labels:
      ho.ctf.cyrhades: "1"
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: "baddev"
      FTP_USER_PASS: "trucdeOufCePassword"
      FTP_USER_HOME: "/home/documents"
    restart: on-failure
  composer:
    container_name: composer_install
    image: composer
    volumes:
      - web:/app
    command: composer install --ignore-platform-reqs
volumes:
  web: